=== sulu-cmf/sulu/src/Sulu/Component/Content/Template/Resources/schema/template/template-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/template/template"
           xmlns="http://schemas.sulu.io/template/template"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="template" type="templateType"/>

    <xs:complexType name="templateType">
        <xs:sequence>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="xs:string" name="view"/>
            <xs:element type="xs:string" name="controller"/>
            <xs:element type="xs:integer" name="cacheLifetime"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:sequence>
            <xs:element type="propertyType" name="property" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="propertyType" mixed="true">
        <xs:sequence>
            <xs:element type="paramsType" name="params" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:byte" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:byte" name="maxOccurs" use="optional"/>
    </xs:complexType>

    <xs:complexType name="paramsType">
        <xs:sequence>
            <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paramType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
                <xs:attribute type="xs:string" name="value" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== sulu-cmf/sulu/tests/Resources/DataFixtures/Template/template_block.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>complex</key>

    <view>ClientWebsiteBundle:Website:complex.html.twig</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>4800</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="true"/>
        <property name="url" type="resource_locator" mandatory="true"/>
        <property name="article" type="text_editor" mandatory="true"/>
        <block name="block1" minOccurs="2" maxOccurs="10" mandatory="true">
            <properties>
                <property name="title1.1" type="text_line" mandatory="true"/>
                <property name="article1.1" type="text_area" mandatory="true" minOccurs="2"/>
                <block name="block1.1">
                    <properties>
                        <block name="block1.1.1">
                            <properties>
                                <property name="article1.1.1" type="text_area" mandatory="true" minOccurs="2"/>
                                <property name="article2.1.2" type="text_area" mandatory="true" minOccurs="2"/>
                                <block name="block1.1.3">
                                    <properties>
                                        <property name="article1.1.3.1" type="text_area" mandatory="true"
                                                  minOccurs="2"/>
                                    </properties>
                                </block>
                            </properties>
                        </block>
                        <block name="block1.1.2">
                            <properties>
                                <property name="article1.1.2.1" type="text_area" mandatory="true" minOccurs="2"/>
                            </properties>
                        </block>
                    </properties>
                </block>
            </properties>
        </block>
        <property name="blog" type="text_editor" mandatory="true"/>
    </properties>
</template>
