=== sulu-cmf/sulu/src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/template/template"
           xmlns="http://schemas.sulu.io/template/template"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    Import XML namespace (used by xincludes)
    -->
    <xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='xml.xsd'/>

    <xs:element name="properties" type="rootPropertiesType"/>

    <!--
    Attribute group for attributes that are allowed for all elements
    -->
    <xs:attributeGroup name="defaultAttributes">
        <xs:anyAttribute namespace='http://www.w3.org/XML/1998/namespace'/>
    </xs:attributeGroup>

    <xs:complexType name="metaType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="langType" name="title"/>
            <xs:element type="langType" name="info_text"/>
            <xs:element type="langType" name="placeholder"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="areasType">
        <xs:sequence>
            <xs:element type="areaContextType" name="area" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="areaContextType">
        <xs:sequence>
            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="langType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" use="required" type="xs:string"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rootPropertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element type="blockType" name="block" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="sectionType" name="section" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="sectionType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attribute type="xs:string" name="disabledCondition" use="optional"/>
        <xs:attribute type="xs:string" name="visibleCondition" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property"/>
            <xs:element type="blockType" name="block"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertyType" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="paramsType" name="params" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="indexField" minOccurs="0" maxOccurs="1"/>
        </xs:choice>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute name="onInvalid" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ignore"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attribute type="xs:integer" name="size" use="optional"/>
        <xs:attribute type="xs:integer" name="spaceAfter" use="optional"/>
        <xs:attribute type="xs:string" name="disabledCondition" use="optional"/>
        <xs:attribute type="xs:string" name="visibleCondition" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="blockTypesType" name="types" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="default-type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attribute type="xs:string" name="disabledCondition" use="optional"/>
        <xs:attribute type="xs:string" name="visibleCondition" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypesType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="blockTypeType" name="type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypeType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="tagType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:int" name="priority" use="optional"/>
                <xs:anyAttribute namespace="##any" processContents="lax"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="paramsType">
        <xs:sequence>
            <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="paramType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="meta" type="metaType" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute name="type" type="paramTypeType" default="string"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="optional"/>
        <xs:attribute name="expression" type="xs:string" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:simpleType name="paramTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="collection"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== sulu-cmf/sulu/src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
<?xml version="1.0" ?>
<properties xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/properties-1.0.xsd">
    <section name="avatar" colspan="4">
        <properties>
            <property name="avatar" type="single_media_upload" label="false">
                <params>
                    <param name="upload_text">
                        <meta>
                            <info_text lang="en">Drop image or click to change avatar</info_text>
                            <info_text lang="de">Bild ablegen oder klicken um das Avatar zu Ã¤ndern</info_text>
                        </meta>
                    </param>
                    <param name="skin" value="round"/>
                    <param name="empty_icon" value="su-user"/>
                    <param name="collection_id" expression="service('sulu_media.system_collections.manager').getSystemCollection('sulu_contact.contact')"/>
                </params>
            </property>
        </properties>
    </section>
    <section name="contact" colspan="8">
        <properties>
            <property name="formOfAddress" type="single_select" mandatory="true" colspan="3" spaceAfter="9">
                <meta>
                    <title lang="en">Salutation</title>
                    <title lang="de">Anrede</title>
                </meta>
                <params>
                    <param name="default_value" value="0"/>
                    <param name="values" type="collection">
                        <param name="0" value="0">
                            <meta>
                                <title lang="en">Mr.</title>
                                <title lang="de">Herr</title>
                            </meta>
                        </param>
                        <param name="1" value="1">
                            <meta>
                                <title lang="en">Ms.</title>
                                <title lang="de">Frau</title>
                            </meta>
                        </param>
                    </param>
                </params>
            </property>

            <property name="firstName" type="text_line" mandatory="true" colspan="6">
                <meta>
                    <title lang="en">First Name</title>
                    <title lang="de">Vorname</title>
                </meta>
            </property>

            <property name="lastName" type="text_line" mandatory="true" colspan="6">
                <meta>
                    <title lang="en">Last Name</title>
                    <title lang="de">Nachname</title>
                </meta>
            </property>

            <property name="account" type="single_account_selection" colspan="6">
                <meta>
                    <title lang="en">Organization</title>
                    <title lang="de">Organisation</title>
                </meta>
            </property>

            <property name="salutation" type="text_line">
                <meta>
                    <title lang="en">Salutation</title>
                    <title lang="de">Anrede</title>
                </meta>
            </property>
        </properties>
    </section>
</properties>
