=== sulu-cmf/sulu/src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/template/template"
           xmlns="http://schemas.sulu.io/template/template"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    Import XML namespace (used by xincludes)
    -->
    <xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='xml.xsd'/>

    <xs:include schemaLocation="properties-1.0.xsd"/>

    <xs:element name="template" type="templateType"/>

    <xs:complexType name="templateType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="xs:string" name="key" minOccurs="1" maxOccurs="1"/>
            <xs:element type="indexType" name="index" minOccurs="1" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" maxOccurs="unbounded"/>
            <xs:element type="xs:string" name="view" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="controller" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="internal" minOccurs="0" maxOccurs="1"/>
            <xs:element type="cacheLifetimeType" name="cacheLifetime" minOccurs="1" maxOccurs="1"/>
            <xs:element type="areasType" name="areas"/>
            <xs:element type="rootPropertiesType" name="properties" minOccurs="1" maxOccurs="1"/>

            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                    </xs:choice>
                    <xs:attributeGroup ref="defaultAttributes"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="cacheLifetimeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" default="seconds">
                    <xs:simpleType>
                        <xs:union memberTypes="cacheLifetimeTypeEnum cacheLifetimeTypeAnyString"/>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="cacheLifetimeTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="seconds"/>
            <xs:enumeration value="expression"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cacheLifetimeTypeAnyString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="indexType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== sulu-cmf/sulu/src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/blocks/text_block.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>text_block</key>

    <meta>
        <title lang="en">Text Block</title>
        <title lang="de">Text Block</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

        </property>

        <property name="description" type="text_editor">
            <meta>
                <title lang="en">Description</title>
                <title lang="de">Beschreibung</title>
            </meta>
        </property>

        <block name="blocks" default-type="editor" minOccurs="0">
            <types>
                <type ref="text_block2" />
                <type name="editor">
                    <meta>
                        <title lang="en">Editor</title>
                        <title lang="de">Editor</title>
                    </meta>
                    <properties>
                        <property name="text_editor" type="text_editor">
                            <meta>
                                <title lang="en">Text Editor</title>
                                <title lang="de">Texteditor</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
    </properties>
</template>

=== sulu-cmf/sulu/src/Sulu/Bundle/CoreBundle/Content/templates/external-link.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>external-link</key>

    <controller>not in use</controller>
    <view>not in use</view>
    <cacheLifetime>1</cacheLifetime>
    <internal>true</internal>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>
            </meta>
        </property>

        <property name="external" type="url">
            <meta>
                <title lang="de">Link</title>
                <title lang="en">Link</title>
            </meta>
            <tag name="sulu.rlp"/>
        </property>
    </properties>
</template>

=== sulu-cmf/sulu/src/Sulu/Bundle/ContentBundle/Tests/app/Resources/snippets/hotel.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd"
          >

    <key>hotel</key>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Name</title>
                <title lang="en">Name</title>
            </meta>

            <tag name="sulu.search.field" role="title" />

            <tag name="sulu.node.name"/>
            <tag name="sulu.rlp.part"/>
        </property>

        <property name="photo" type="media_selection" mandatory="false">
            <meta>
                <title lang="de">Foto</title>
                <title lang="en">Photo</title>
            </meta>
        </property>

        <property name="description" type="text_editor">
            <meta>
                <title lang="de">Beschreibung</title>
                <title lang="en">Description</title>
            </meta>

            <tag name="sulu.search.field" role="description" />
        </property>
    </properties>
</template>

=== sulu-cmf/sulu/src/Sulu/Bundle/ContentBundle/Tests/Application/config/templates/pages/complex.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd"
          >

    <key>complex</key>

    <view>ClientWebsiteBundle:templates:animals</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <meta>
        <title lang="de">Tiers</title>
        <title lang="en">Animals</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Tier</title>
                <title lang="en">Animals</title>
            </meta>

            <tag name="sulu.rlp.part"/>
        </property>

        <property name="url" type="resource_locator" mandatory="true">
            <meta>
                <title lang="de">Adresse</title>
                <title lang="en">Resourcelocator</title>
            </meta>

            <tag name="sulu.rlp"/>
        </property>

        <block name="block1" 
               default-type="editor"
               minOccurs="2"
               maxOccurs="10"
               mandatory="true">
            <meta>
                <title lang="de">Block</title>
                <title lang="en">Block</title>
            </meta>
            <types>
                <type name="default">
                    <meta>
                        <title lang="de">Texteditor</title>
                        <title lang="en">Text editor</title>
                    </meta>
                    <properties>
                        <property name="title" type="text_line" mandatory="true">
                            <meta>
                                <title lang="de">Titel</title>
                                <title lang="en">Title</title>
                            </meta>
                        </property>
                        <property name="article" type="text_editor" mandatory="true">
                            <meta>
                                <title lang="de">Artikel</title>
                                <title lang="en">Article</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
    </properties>
</template>
