=== sulu-cmf/sulu/src/Sulu/Component/Workspace/Loader/schema/workspace/workspace-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/workspace/workspace" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://schemas.sulu.io/workspace/workspace">
    <xs:complexType name="workspaceType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="localizationsType" name="localizations"/>
            <xs:element type="segmentsType" name="segments" maxOccurs="1" minOccurs="0"/>
            <xs:element type="themeType" name="theme"/>
            <xs:element type="portalsType" name="portals"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="localizationsType">
        <xs:sequence>
            <xs:element type="localizationType" name="localization" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="localizationType" mixed="true">
        <xs:sequence>
            <xs:element type="localizationType" name="localization" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="language" use="required"/>
        <xs:attribute type="xs:string" name="country" use="optional"/>
        <xs:attribute name="shadow" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="auto"/>
                    <xs:enumeration value="none"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="segmentsType">
        <xs:sequence>
            <xs:element type="segmentType" name="segment" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="segmentType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="key" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="portalsType">
        <xs:sequence>
            <xs:element type="portalType" name="portal" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="portalType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="resource-locatorType" name="resource-locator"/>
            <xs:element type="localizationsType" name="localizations" minOccurs="0" maxOccurs="1"/>
            <xs:element type="environmentsType" name="environments"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="resource-locatorType">
        <xs:sequence>
            <xs:element type="xs:string" name="strategy"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="themeType">
        <xs:sequence>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="excludedType" name="excluded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="excludedType">
        <xs:sequence>
            <xs:element type="xs:string" name="template" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="environmentsType">
        <xs:sequence>
            <xs:element type="environmentType" name="environment" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="environmentType">
        <xs:sequence>
            <xs:element type="urlsType" name="urls"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="type" use="optional"/>
    </xs:complexType>
    <xs:complexType name="urlsType">
        <xs:sequence>
            <xs:element type="urlType" name="url" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="urlType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="language" use="optional"/>
                <xs:attribute type="xs:string" name="country" use="optional"/>
                <xs:attribute type="xs:string" name="segment" use="optional"/>
                <xs:attribute type="xs:string" name="redirect" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="workspace" type="workspaceType"/>
</xs:schema>

=== sulu-cmf/sulu/tests/Resources/DataFixtures/Workspace/valid/sulu.io_withoutPortalLocalization.xml
<?xml version="1.0" encoding="utf-8"?>
<workspace xmlns="http://schemas.sulu.io/workspace/workspace"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://schemas.sulu.io/workspace/workspace http://schemas.sulu.io/workspace/workspace-1.0.xsd">

    <name>Sulu CMF</name>
    <key>sulu_io_without_portal_localization</key>

    <localizations>
        <localization language="en" country="us" shadow="auto">
            <localization language="en" country="uk" />
        </localization>
        <localization language="de" country="at"/>
    </localizations>

    <portals>
        <portal>
            <name>Sulu CMF AT</name>
            <key>sulucmf_withoutportallocalizations_at</key>
            <resource-locator>
                <strategy>short</strategy>
            </resource-locator>

            <theme>
                <key>sulu</key>
                <excluded>
                    <template>overview</template>
                </excluded>
            </theme>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="de" country="at">sulu-without.at</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="de" country="at">sulu-without.lo</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</workspace>
