=== sulu-cmf/sulu/src/Sulu/Bundle/MediaBundle/Media/FormatLoader/schema/formats/formats-1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/media/formats" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://schemas.sulu.io/media/formats" xmlns:mf="http://schemas.sulu.io/media/formats"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="formatsType">
        <xs:sequence>
            <xs:element name="format" type="formatType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="formatType">
        <xs:sequence>
            <xs:element name="meta" type="metaType" minOccurs="0">
                <xs:unique name="langUnique">
                    <xs:selector xpath="mf:title"/>
                    <xs:field xpath="@lang"/>
                </xs:unique>
            </xs:element>
            <xs:element name="scale" type="scaleType"/>
            <xs:element name="transformations" type="transformationsType" minOccurs="0"/>
            <xs:element type="optionsType" name="options" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required"/>
        <xs:attribute name="internal" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="optionsType">
        <xs:sequence>
            <xs:element type="parameterType" name="option" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="metaType">
        <xs:sequence>
            <xs:element name="title" type="titleType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="scaleType">
        <xs:attribute name="x" type="xs:positiveInteger"/>
        <xs:attribute name="y" type="xs:positiveInteger"/>
        <xs:attribute name="mode" type="modeType"/>
        <xs:attribute name="retina" type="xs:boolean"/>
        <xs:attribute name="forceRatio" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="transformationsType">
        <xs:sequence>
            <xs:element name="transformation" type="transformationType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="titleType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="modeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="inset"/>
            <xs:enumeration value="outbound"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="transformationType">
        <xs:sequence>
            <xs:element name="effect" type="xs:string"/>
            <xs:element name="parameters" type="parametersType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parametersType">
        <xs:sequence>
            <xs:element name="parameter" type="parameterType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="formats" type="formatsType">
        <xs:key name="formatKey">
            <xs:selector xpath="mf:format"/>
            <xs:field xpath="@key"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== sulu-cmf/sulu/src/Sulu/Bundle/MediaBundle/Tests/Fixtures/image-formats/version11_missing_dimension.xml
<?xml version="1.0" encoding="UTF-8"?>
<formats xmlns="http://schemas.sulu.io/media/formats"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://schemas.sulu.io/media/formats http://schemas.sulu.io/media/formats-1.1.xsd">

    <format key="400x400">
        <scale/>
        <transformations>
            <transformation>
                <effect>blur</effect>
                <parameters>
                    <parameter name="type">gaussian</parameter>
                    <parameter name="kernel">20</parameter>
                </parameters>
            </transformation>
        </transformations>
        <options>
            <option name="jpeg_quality">70</option>
            <option name="png_compression_level">6</option>
        </options>
    </format>

    <format key="400x-inset">
        <meta>
            <title lang="en">My 400 Format</title>
            <title lang="de">Mein 400 Format</title>
        </meta>
        <scale x="400"/>
        <options>
            <option name="jpeg_quality">70</option>
        </options>
    </format>

    <format key="200x180-inset">
        <scale x="200" y="180"/>
    </format>
</formats>

=== sulu-cmf/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/image-formats-v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<formats xmlns="http://schemas.sulu.io/media/formats"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://schemas.sulu.io/media/formats http://schemas.sulu.io/media/formats-1.1.xsd">

    <format key="sulu-25x25" internal="true">
        <meta>
            <title lang="en">Small thumbnail (Sulu-V2)</title>
            <title lang="de">Kleines Thumbnail (Sulu-V2)</title>
            <title lang="fr">Image miniature (Sulu-V2)</title>
            <title lang="nl">Kleine thumbnail (Sulu-V2)</title>
        </meta>
        <scale x="25" y="25"/>
    </format>
</formats>

=== sulu-cmf/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/image-formats.xml
<?xml version="1.0" encoding="UTF-8"?>
<formats xmlns="http://schemas.sulu.io/media/formats"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://schemas.sulu.io/media/formats http://schemas.sulu.io/media/formats-1.1.xsd">

    <!-- These image formats are deprecated -->
    <format key="sulu-400x400" internal="true">
        <meta>
            <title lang="en">Contact avatar (Sulu)</title>
            <title lang="de">Kontaktavatar (Sulu)</title>
            <title lang="fr">Avatar du contact (Sulu)</title>
            <title lang="nl">Contact avatar (Sulu)</title>
        </meta>
        <scale x="400" y="400"/>
    </format>
    <format key="sulu-260x" internal="true">
        <meta>
            <title lang="en">Masonry preview (Sulu)</title>
            <title lang="de">Masonry Vorschau (Sulu)</title>
            <title lang="fr">Prévisualisation maçonnerie (Sulu)</title>
            <title lang="nl">Masonry voorbeeld (Sulu)</title>
        </meta>
        <scale x="260"/>
    </format>
    <format key="sulu-170x170" internal="true">
        <meta>
            <title lang="en">Search (Sulu)</title>
            <title lang="de">Suche (Sulu)</title>
            <title lang="fr">Recherche (Sulu)</title>
            <title lang="nl">Zoeken (Sulu)</title>
        </meta>
        <scale x="170" y="170"/>
    </format>
    <format key="sulu-100x100-inset" internal="true">
        <meta>
            <title lang="en">Organization card (Sulu)</title>
            <title lang="de">Organisationskarte (Sulu)</title>
            <title lang="fr">Carte d'organisation (Sulu)</title>
            <title lang="nl">Organisatie kaart (Sulu)</title>
        </meta>
        <scale x="100" y="100" mode="inset"/>
    </format>
    <format key="sulu-50x50" internal="true">
        <meta>
            <title lang="en">Small thumbnail (Sulu)</title>
            <title lang="de">Kleines Thumbnail (Sulu)</title>
            <title lang="fr">Image miniature (Sulu)</title>
            <title lang="nl">Kleine thumbnail (Sulu)</title>
        </meta>
        <scale x="50" y="50"/>
    </format>
    <!-- End of deprecated image formats -->
    <format key="sulu-25x25" internal="true">
        <meta>
            <title lang="en">Micro thumbnail</title>
            <title lang="de">Mikro Thumbnail</title>
            <title lang="fr">Image micro</title>
            <title lang="nl">Micro thumbnail</title>
        </meta>
        <scale x="25" y="25"/>
    </format>
    <format key="sulu-40x40" internal="true">
        <meta>
            <title lang="en">Small thumbnail (Sulu)</title>
            <title lang="de">Kleines Thumbnail (Sulu)</title>
            <title lang="fr">Image miniature (Sulu)</title>
            <title lang="nl">Kleine thumbnail (Sulu)</title>
        </meta>
        <scale x="40" y="40"/>
    </format>
    <format key="sulu-240x" internal="true">
        <meta>
            <title lang="en">Masonry preview (Sulu)</title>
            <title lang="de">Masonry Vorschau (Sulu)</title>
            <title lang="fr">Prévisualisation maçonnerie (Sulu)</title>
            <title lang="nl">Masonry voorbeeld (Sulu)</title>
        </meta>
        <scale x="240"/>
    </format>
    <format key="sulu-400x400-inset" internal="true">
        <meta>
            <title lang="en">Organization logo (Sulu)</title>
            <title lang="de">Organisationslogo (Sulu)</title>
            <title lang="fr">Logo d'organisation (Sulu)</title>
            <title lang="nl">Organisatie logo (Sulu)</title>
        </meta>
        <scale x="400" y="400" mode="inset"/>
    </format>
    <format key="sulu-100x100" internal="true">
        <meta>
            <title lang="en">Contact card (Sulu)</title>
            <title lang="de">Personenkarte (Sulu)</title>
            <title lang="fr">Carte personnelle (Sulu)</title>
            <title lang="nl">Contact kaart (Sulu)</title>
        </meta>
        <scale x="100" y="100"/>
    </format>
</formats>
