=== sulu-cmf/sulu/src/Sulu/Component/Portal/Loader/schema/portal/portal-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/portal/portal"
           xmlns="http://schemas.sulu.io/portal/portal"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="portalType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="languagesType" name="languages"/>
            <xs:element type="themeType" name="theme"/>
            <xs:element type="environmentsType" name="environments"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="languagesType">
        <xs:sequence>
            <xs:element type="languageType" name="language" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="languageType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:boolean" name="main"/>
                <xs:attribute type="xs:boolean" name="fallback"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="themeType">
        <xs:sequence>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="excludedType" name="excluded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="excludedType">
        <xs:sequence>
            <xs:element type="xs:string" name="template" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="environmentsType">
        <xs:sequence>
            <xs:element type="environmentType" name="environment" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="environmentType">
        <xs:sequence>
            <xs:element type="urlsType" name="urls"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="type"/>
    </xs:complexType>
    <xs:complexType name="urlsType">
        <xs:sequence>
            <xs:element type="urlType" name="url" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="urlType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:boolean" name="main"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="portal" type="portalType"/>
</xs:schema>

=== sulu-cmf/sulu/tests/Resources/DataFixtures/Portal/valid/massiveart.xml
<?xml version="1.0" encoding="utf-8"?>
<portal xmlns="http://schemas.sulu.io/portal/portal"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://schemas.sulu.io/portal/portal http://schemas.sulu.io/portal/portal-1.0.xsd">

    <name>Massive Art</name>
    <key>massiveart</key>

    <languages>
        <language main="true">en</language>
        <language fallback="true">de</language>
    </languages>

    <theme>
        <key>massiveart</key>
        <excluded>
            <template>overview</template>
        </excluded>
    </theme>

    <environments>
        <environment type="prod">
            <urls>
                <url main="true">massiveart.com</url>
                <url>www.massiveart.com</url>
            </urls>
        </environment>
        <environment type="dev">
            <urls>
                <url main="true">massiveart.lo</url>
            </urls>
        </environment>
    </environments>
</portal>
